version: "3"
silent: true
tasks:
  default:
    desc: List all tasks
    cmds:
      - task --list
  build:
    desc: Builds the docker image
    cmds:
      - docker build -f deployment/Dockerfile -t aeswibon/helm-deployer:latest .
  push:
    desc: Pushes the docker image to docker hub
    cmds:
      - task: build
      - docker image push aeswibon/helm-deployer:latest
  deploy:
    desc: Deploys the application to kubernetes
    cmds:
      - kubectl apply -f deployment/pvc.yaml
      - kubectl apply -f deployment/deployment.yaml
      - kubectl apply -f deployment/service.yaml
  clean:
    desc: Cleans the docker image
    cmds:
      - docker rmi aeswibon/helm-deployer:latest
  delete:
    desc: Deletes the application from kubernetes
    cmds:
      - kubectl delete -f deployment/deployment.yaml
      - kubectl delete -f deployment/service.yaml
      - kubectl delete -f deployment/pvc.yaml
      - task: clean
  logs:
    desc: Shows the logs of the application
    cmds:
      - kubectl logs -l app=helm-deployer
