apiVersion: apps/v1
kind: Deployment
metadata:
  name: shepherd
spec:
  replicas: 1
  selector:
    matchLabels:
      app: shepherd
  template:
    metadata:
      labels:
        app: shepherd
    spec:
      containers:
        - name: shepherd
          image: aeswibon/shepherd:latest
          ports:
            - containerPort: 8080
          env:
            - name: DB_HOST
              valueFrom:
                secretKeyRef:
                  name: shepherd-config
                  key: DB_HOST
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: shepherd-config
                  key: DB_USER
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: shepherd-config
                  key: DB_PASSWORD
            - name: DB_NAME
              valueFrom:
                secretKeyRef:
                  name: shepherd-config
                  key: DB_NAME
            - name: DB_PORT
              valueFrom:
                secretKeyRef:
                  name: shepherd-config
                  key: DB_PORT
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: shepherd-config
                  key: JWT_SECRET
          resources:
            limits:
              cpu: "1"
              memory: "512Mi"
            requests:
              cpu: "100m"
              memory: "256Mi"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: shepherd-db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: shepherd-db
  template:
    metadata:
      labels:
        app: shepherd-db
    spec:
      containers:
        - name: shepherd-db
          image: postgres:alpine
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_DB
              valueFrom:
                secretKeyRef:
                  name: shepherd-config
                  key: DB_NAME
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: shepherd-config
                  key: DB_USER
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: shepherd-config
                  key: DB_PASSWORD
          resources:
            limits:
              cpu: "1"
              memory: "512Mi"
          volumeMounts:
            - name: shepherd-storage
              mountPath: /var/lib/postgresql/data
      volumes:
        - name: shepherd-storage
          persistentVolumeClaim:
            claimName: shepherd-pvc
