apiVersion: v1
kind: Secret
metadata:
  name: shepherd-config
type: Opaque
data:
  DB_HOST: postgres
  DB_USER: postgres
  DB_PASSWORD: postgres
  DB_NAME: helm
  DB_PORT: "5432"
  JWT_SECRET: c2VjcmV0LWRiLWp3dC1zZWNyZXQ=
