apiVersion: v1
kind: Service
metadata:
  name: shepherd-svc
spec:
  selector:
    app: shepherd
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: LoadBalancer
---
apiVersion: v1
kind: Service
metadata:
  name: shepherd-db-svc
spec:
  selector:
    app: shepherd-db
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432
